import { canonicalVendor } from "@/lib/vendors";
import { BRAND_LOGOS } from "@/lib/brand-logos";

/**
 * Official vendor marks, so the table can be scanned by company before a single
 * model name is read.
 *
 * The paths live in lib/brand-logos.ts, generated by scripts/fetch-logos.ts and
 * committed — the site is static and must not depend on a CDN at runtime.
 *
 * Monochrome marks inherit `currentColor`, which keeps them subordinate to the
 * podium colours that carry rank. Google is the exception: its identity is the
 * four-colour G, and rendering it in one colour would be wrong rather than
 * restrained, so `multicolour` marks keep their own hexes.
 *
 * `dangerouslySetInnerHTML` is safe in the strict sense here: the content is a
 * committed, reviewed constant from a build-time fetch, never user input.
 */
export function VendorMark({
  organization,
  size = 15,
  className,
}: {
  organization: string;
  size?: number;
  className?: string;
}) {
  const vendor = canonicalVendor(organization);
  const logo = vendor ? BRAND_LOGOS[vendor] : undefined;

  if (!logo) {
    // A vendor with no mark gets a neutral placeholder rather than a gap, and
    // lib/score.test.ts asserts this branch is unreachable for real data.
    return (
      <svg width={size} height={size} viewBox="0 0 16 16" className={className} aria-hidden="true">
        <circle cx="8" cy="8" r="4.6" fill="none" stroke="currentColor" strokeWidth="1.5" />
      </svg>
    );
  }

  return (
    <svg
      width={size}
      height={size}
      viewBox={logo.viewBox}
      className={className}
      role="img"
      aria-label={vendor ?? organization}
      // The OpenAI and Grok paths carry no fill of their own, so without this
      // they default to black and vanish on the dark page. Google's paths set
      // their own hexes and ignore this anyway, but leaving it off is clearer.
      fill={logo.multicolour ? undefined : "currentColor"}
      dangerouslySetInnerHTML={{ __html: logo.body }}
    />
  );
}
