/**
 * Regenerates lib/brand-logos.ts from the Iconify API.
 *
 * The logos are fetched once and COMMITTED, not fetched at runtime — the site is
 * static and must not depend on a third-party CDN being up. Re-run this only
 * when a vendor rebrands or a new vendor appears:
 *
 *   npx tsx scripts/fetch-logos.ts
 *
 * Sources are chosen per vendor rather than from one set, because no single set
 * carries all of them: simple-icons has no OpenAI or xAI/Grok mark, and Google's
 * identity is inherently multicolour so the `logos` set's four-path version is
 * the honest one.
 */
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

const SOURCES: { vendor: string; icon: string; note: string }[] = [
  { vendor: "Anthropic", icon: "simple-icons/anthropic", note: "monochrome wordmark glyph" },
  { vendor: "OpenAI", icon: "logos/openai-icon", note: "the blossom; simple-icons has no OpenAI" },
  // The models are literally named kimi-*, so the product brand is what a reader
  // recognises — not the parent company's Moonshot mark.
  { vendor: "Moonshot", icon: "simple-icons/kimi", note: "Kimi, the product brand" },
  { vendor: "xAI", icon: "logos/grok-icon", note: "Grok mark; simple-icons has no xAI" },
  { vendor: "Meta", icon: "simple-icons/meta", note: "infinity loop" },
  { vendor: "Google", icon: "logos/google-icon", note: "official four-colour G" },
  { vendor: "Z.ai", icon: "simple-icons/zdotai", note: "" },
  // Same reasoning as Moonshot/Kimi: the models ship as qwen*, so Qwen is the
  // brand a reader recognises, not the parent company's mark.
  { vendor: "Alibaba", icon: "simple-icons/qwen", note: "Qwen, the model brand" },
  { vendor: "DeepSeek", icon: "simple-icons/deepseek", note: "" },
];

async function main() {
  const entries: string[] = [];

  for (const { vendor, icon, note } of SOURCES) {
    const url = `https://api.iconify.design/${icon}.svg`;
    const res = await fetch(url);
    if (!res.ok) throw new Error(`${icon}: HTTP ${res.status}`);
    const svg = await res.text();

    const viewBox = /viewBox="([^"]+)"/.exec(svg)?.[1];
    const body = /<svg[^>]*>([\s\S]*)<\/svg>/.exec(svg)?.[1]?.trim();
    if (!viewBox || !body) throw new Error(`${icon}: could not parse`);

    // A mark with no explicit fill inherits currentColor and can be tinted;
    // one that hardcodes hexes (Google) must keep them.
    const multicolour = /fill="#/.test(body);
    const clean = body.replace(/\s+/g, " ");

    console.log(
      `  ${vendor.padEnd(11)} ${icon.padEnd(26)} ${multicolour ? "multicolour" : "monochrome "} ${clean.length} chars`,
    );

    entries.push(
      `  ${JSON.stringify(vendor)}: {\n` +
        `    // ${icon}${note ? ` — ${note}` : ""}\n` +
        `    viewBox: ${JSON.stringify(viewBox)},\n` +
        `    multicolour: ${multicolour},\n` +
        `    body: ${JSON.stringify(clean)},\n` +
        `  },`,
    );
  }

  const out = `/**
 * GENERATED by scripts/fetch-logos.ts — do not edit by hand.
 *
 * Official vendor marks, fetched once from the Iconify API and committed so the
 * site stays static and offline-capable. \`multicolour\` marks carry their own
 * brand hexes and must not be tinted; the rest inherit currentColor.
 *
 * These are third-party trademarks, used here to identify each company's models
 * in a comparison. They are not covered by this project's licence.
 */
export interface BrandLogo {
  viewBox: string;
  multicolour: boolean;
  body: string;
}

export const BRAND_LOGOS: Record<string, BrandLogo> = {
${entries.join("\n")}
};
`;

  const path = resolve(process.cwd(), "lib/brand-logos.ts");
  writeFileSync(path, out);
  console.log(`\n  Wrote lib/brand-logos.ts (${SOURCES.length} vendors)\n`);
}

main().catch((e) => {
  console.error(`\n  FAILED: ${(e as Error).message}\n`);
  process.exit(1);
});
